name: barcode_scan_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mobile_scanner: ^3.2.0
  barcode_widget: ^2.0.4
  barcode: ^2.2.9
  web_scraper: ^0.1.4
  url_launcher: ^6.3.1
  path_provider: ^2.0.11

  animated_splash_screen: ^1.3.0
  get: ^4.7.2

  sqflite: ^2.0.0+3
  path: ^1.8.0

  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^10.1.4
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  

flutter_icons:
  image_path: "assets/icon.png"
  android:  true

flutter:
  uses-material-design: true
  assets:
    - assets/

